apiVersion: v1
kind: Namespace
metadata:
  name: developpement
  labels:
    name: developpement
[node1 ~]$ cat service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  type: NodePort
  selector:
    app: web-red
  ports:
    - targetPort: 8080    
      port: 8080
      nodePort: 30008
